### ISSUE TITLE
SVF Build Fail-missing .config.in

### ISSUE THREAD

**Issue by lxyyyy09** [sslab-skku/RustSan#3]
Hi. I'm trying to build SVF with command './build.sh'.Then it showed 
```
CMake Error: File /home/monsoon/RustSan_SVF/RustSan/SVF/.config.in does not exist.
CMake Error at CMakeLists.txt:6 (configure_file):
  configure_file Problem configuring file
```
It looks like this file does not exit yet. Where should I found that file? Or is there any vars I should change?

**Comment by ChoKyuWon** [comment]
Hi, I guess the file name starts with a dot, so my git just ignores it.
I fixed the git ignore and pushed the file where I used it.

**Comment by lxyyyy09** [comment]
thx
